# Generated by Django 5.2.7 on 2025-11-28 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
