# Generated by Django 5.2.7 on 2025-11-12 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('theater', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
