# Generated by Django 5.2.7 on 2025-12-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('theatres', '0004_showseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatres.show'),
        ),
    ]
