# Generated by Django 5.2.7 on 2025-11-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Horror', 'Horror')], max_length=20)),
                ('poster', models.ImageField(default='posters/default.jpg', upload_to='posters/')),
                ('date', models.DateField(null=True)),
                ('release_date', models.DateField(default=None)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
    ]
