# Generated by Django 5.2.7 on 2025-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Horror', 'Horror'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Music', 'Music'), ('Romance', 'Romance'), ('SciFi', 'Scifi'), ('Thriller', 'Thriller')], max_length=20),
        ),
    ]
